### ISSUE TITLE
[EC69] - check relevance of this rule

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-csharp#16]
like in python issue https://github.com/green-code-initiative/ecoCode-python/issues/21, check if implemented EC69 rule in C# plugin is relevant or not

**Comment by Djoums** [comment]
For loops in Python match foreach loops in C#, and don't trigger a warning with our rule implementation.
```
foreach (int i in Enumerable.Range(0, 10)) // Compliant, evaluated once
```

For loops however are equivalent to for loops in C/C++, and evaluate function calls in conditions at every iteration, this is what our rule covers.
```
for (int i = 0; i < GetValue(); i++) // Non compliant, loop invariant function in loop condition
```
This is also the case for while and do-while loops, our rule implementation cover those too.
