### ISSUE TITLE
[EC 86] GC.Collect should not be called

### ISSUE THREAD

**Issue by GregoireBo** [green-code-initiative/ecoCode-csharp#36]
Hi all, on @Djoums advice, I suggest to add this rule.
Sonar already implements this rule, see it here : https://cloud-ci.sgs.com/sonar/coding_rules?open=csharpsquid%3AS1215&rule_key=csharpsquid%3AS1215

**Category : Performance**
**Severity : Warning**

## Why is this an issue
GC.Collect() is a method, often unecessary that could affect performances. It will trigger a blocking operation that will analyze every objects that are in memory in order to execute the cleanup.

## When can it be ignored ?

- If the specified generation is 0, in this case it should be harmless
- If a special event in your program caused a lot of long-lived objects to die

## Non-compliant Code Example
 ```C#
public static void Main()
{
    GC.Collect() // Non-compliant
}

public static void Main()
{
    GC.Collect(generation: 10) // Non-compliant
}
```
## Compliant Code Example
 ```C#
public static void Main()
{
    GC.Collect(generation: 0); // Compliant
}
```

**Comment by Djoums** [comment]
The rule PR on the main repository : https://github.com/green-code-initiative/ecoCode/pull/289
