### ISSUE TITLE
EC75 on collections ForEach

### ISSUE THREAD

**Issue by natixis-caen** [green-code-initiative/ecoCode-csharp#53]
Rule EC75 - "Don’t concatenate strings in loops, use a StringBuilder instead." doesn't handle LINQ ForEach.

```csharp
using System.Collections.Generic;
public class Test
{
    public static void Run(string s0)
    {
        string s = "";

        List<int> numbers = [ 0, 1, 1, 2, 3, 5, 8, 13 ];

        numbers.ForEach(i => [|s += i|]);
    }
}
```

The code above should throw a warning.

**Comment by Djoums** [comment]
Further analysis, we should support the following calls :
- List<T> : void ForEach(Action<T> action)
- ImmutableList<T> : void ForEach(Action<T> action)
- Array : static void ForEach<T>(T[] array, Action<T> action)
- Tasks.Parallel : there are 20 version of ForEach, the good news is that the argument we care about is always called `body`, which is something we can use in the analyzer.
